function BitcoinPriceUSD = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BITCOINPRICEUSD = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  BITCOINPRICEUSD = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  BitcoinPriceUSD = importfile("C:\Users\NunoS\Ambiente de Trabalho\GitHub\IC-Project\Project\Phase I\Matlab\Bitcoin Price (USD).csv", [188265, 188265]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Nov-2022 19:01:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [188265, 188265];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "QuoteAssetVolume", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14"];
opts.SelectedVariableNames = "QuoteAssetVolume";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "double", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "QuoteAssetVolume", "ThousandsSeparator", ",");

% Import the data
BitcoinPriceUSD = readtable(filename, opts);

end